### ISSUE TITLE
ENHANCEMENT: Duration Tracking Examinations

### ISSUE THREAD

**Issue by tracebackerror** [tracebackerror/swap_le#72]
*Originally reported by* **tracebackerror (Bitbucket: [tracebackerror](https://bitbucket.org/tracebackerror), GitHub: [tracebackerror](https://github.com/tracebackerror))**

----------------------------------------

Current Scenario:  
1. The present system on taking assesment doesn't have implemented duration mechanism.  
2. Take the xamination, one static dialog box in table will be present for implementing duration.

Model Changes:   
  
*  Assement:   
 1. exam_duration (time)  - will store only minutes and hours from UI   
*  Result    
 1. exam_taken_duration (time)  - will store only minutes and hours when assesment is submitted 
    
UI  Changes:   
Templates:   
-- Implement Javascript based **decreasing** timer and **submit** the xam automatically when time is exhausted

-- Use library https://albert-gonzalez.github.io/easytimer.js/
-- OR https://momentjs.com/
-- OR http://countdownjs.org/demo.html

----------------------------------------
- Bitbucket: https://bitbucket.org/tracebackerror/swaple/issue/72

**Comment by vinaykp2499** [comment]
Issue Successfully Resolved
