### ISSUE TITLE
As a developer, I want to enable a Institution registration with an predifined license

### ISSUE THREAD

**Issue by tracebackerror** [tracebackerror/swap_le#89]
1. institute should be able to register
2. Captcha while registration
3. After registration **Account Needs to be confirmed** via email
4. Account Details Submission after registration on email
5. An license to be associated automatically with below details, 👍 

- a. Max Assesment: 200
- b. Max Student: 500
- c. Max Staff: 100
- License Name Format : 
TwoCharCountry-2CharState-ColgName4Char-contactnolast4char-randomno6char
note: dont forgot to strip the spaces and semicolon

**Comment by vinaykp2499** [comment]
Registration Implemented Without Captcha and verification process.
for check commit _**5a56ce3cbd09993291cedfcd3708f13d5e96c501**_
